import Foundation

/// Pure-Swift SHA-1, SHA-256, HMAC and PBKDF2 — no CryptoKit, no CommonCrypto.
///
/// Why this exists in a package that otherwise leans on Apple frameworks:
///
///  - TOTP needs HMAC-SHA1 over a few bytes; a dependency-free implementation
///    behaves identically on every platform the tests run on (macOS + Linux)
///    and its output is pinned by RFC 2202/6238 vectors.
///  - PBKDF2 needs HMAC-SHA256. The production path on Apple platforms is
///    CommonCrypto's `CCKeyDerivationPBKDF` (hardware-accelerated, see
///    `CommonCryptoPbkdf2` in VaultCrypto.swift); this implementation is the
///    injectable fallback that lets `swift test` on Linux verify the exact
///    derivation format against vectors generated by the real web client.
///
/// These are straightforward FIPS 180-4 implementations validated against
/// the standard test vectors in `PureCryptoTests`. They are NOT used for
/// AES-GCM or RSA — those always go through CryptoKit / Security.
public enum PureCrypto {

    // MARK: - SHA-256 (FIPS 180-4)

    public static func sha256(_ message: Data) -> Data {
        var h: [UInt32] = [
            0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
            0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
        ]
        let k: [UInt32] = [
            0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
            0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
            0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
            0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
            0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
            0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
            0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
            0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
        ]

        var padded = message
        let bitLength = UInt64(message.count) &* 8
        padded.append(0x80)
        while padded.count % 64 != 56 { padded.append(0x00) }
        for shift in stride(from: 56, through: 0, by: -8) {
            padded.append(UInt8((bitLength >> UInt64(shift)) & 0xff))
        }

        padded.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            let bytes = raw.bindMemory(to: UInt8.self)
            var w = [UInt32](repeating: 0, count: 64)
            var block = 0
            while block < bytes.count {
                for t in 0..<16 {
                    let i = block + t * 4
                    w[t] = (UInt32(bytes[i]) << 24) | (UInt32(bytes[i + 1]) << 16)
                        | (UInt32(bytes[i + 2]) << 8) | UInt32(bytes[i + 3])
                }
                for t in 16..<64 {
                    let s0 = rotr(w[t - 15], 7) ^ rotr(w[t - 15], 18) ^ (w[t - 15] >> 3)
                    let s1 = rotr(w[t - 2], 17) ^ rotr(w[t - 2], 19) ^ (w[t - 2] >> 10)
                    w[t] = w[t - 16] &+ s0 &+ w[t - 7] &+ s1
                }
                var a = h[0], b = h[1], c = h[2], d = h[3]
                var e = h[4], f = h[5], g = h[6], hh = h[7]
                for t in 0..<64 {
                    let s1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)
                    let ch = (e & f) ^ (~e & g)
                    let temp1 = hh &+ s1 &+ ch &+ k[t] &+ w[t]
                    let s0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)
                    let maj = (a & b) ^ (a & c) ^ (b & c)
                    let temp2 = s0 &+ maj
                    hh = g; g = f; f = e; e = d &+ temp1
                    d = c; c = b; b = a; a = temp1 &+ temp2
                }
                h[0] &+= a; h[1] &+= b; h[2] &+= c; h[3] &+= d
                h[4] &+= e; h[5] &+= f; h[6] &+= g; h[7] &+= hh
                block += 64
            }
        }

        var out = Data(capacity: 32)
        for word in h {
            out.append(UInt8((word >> 24) & 0xff))
            out.append(UInt8((word >> 16) & 0xff))
            out.append(UInt8((word >> 8) & 0xff))
            out.append(UInt8(word & 0xff))
        }
        return out
    }

    // MARK: - SHA-1 (FIPS 180-4; fine for TOTP per RFC 6238)

    public static func sha1(_ message: Data) -> Data {
        var h: [UInt32] = [0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0]

        var padded = message
        let bitLength = UInt64(message.count) &* 8
        padded.append(0x80)
        while padded.count % 64 != 56 { padded.append(0x00) }
        for shift in stride(from: 56, through: 0, by: -8) {
            padded.append(UInt8((bitLength >> UInt64(shift)) & 0xff))
        }

        padded.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            let bytes = raw.bindMemory(to: UInt8.self)
            var w = [UInt32](repeating: 0, count: 80)
            var block = 0
            while block < bytes.count {
                for t in 0..<16 {
                    let i = block + t * 4
                    w[t] = (UInt32(bytes[i]) << 24) | (UInt32(bytes[i + 1]) << 16)
                        | (UInt32(bytes[i + 2]) << 8) | UInt32(bytes[i + 3])
                }
                for t in 16..<80 {
                    w[t] = rotl(w[t - 3] ^ w[t - 8] ^ w[t - 14] ^ w[t - 16], 1)
                }
                var a = h[0], b = h[1], c = h[2], d = h[3], e = h[4]
                for t in 0..<80 {
                    let (f, k): (UInt32, UInt32)
                    switch t {
                    case 0..<20: (f, k) = ((b & c) | (~b & d), 0x5A827999)
                    case 20..<40: (f, k) = (b ^ c ^ d, 0x6ED9EBA1)
                    case 40..<60: (f, k) = ((b & c) | (b & d) | (c & d), 0x8F1BBCDC)
                    default: (f, k) = (b ^ c ^ d, 0xCA62C1D6)
                    }
                    let temp = rotl(a, 5) &+ f &+ e &+ k &+ w[t]
                    e = d; d = c; c = rotl(b, 30); b = a; a = temp
                }
                h[0] &+= a; h[1] &+= b; h[2] &+= c; h[3] &+= d; h[4] &+= e
                block += 64
            }
        }

        var out = Data(capacity: 20)
        for word in h {
            out.append(UInt8((word >> 24) & 0xff))
            out.append(UInt8((word >> 16) & 0xff))
            out.append(UInt8((word >> 8) & 0xff))
            out.append(UInt8(word & 0xff))
        }
        return out
    }

    // MARK: - HMAC (RFC 2104; block size 64 for both SHA-1 and SHA-256)

    public static func hmacSHA1(key: Data, message: Data) -> Data {
        hmac(key: key, message: message, hash: sha1, blockSize: 64)
    }

    public static func hmacSHA256(key: Data, message: Data) -> Data {
        hmac(key: key, message: message, hash: sha256, blockSize: 64)
    }

    private static func hmac(key: Data, message: Data, hash: (Data) -> Data, blockSize: Int) -> Data {
        var k = key.count > blockSize ? hash(key) : key
        if k.count < blockSize { k.append(Data(repeating: 0, count: blockSize - k.count)) }
        var inner = Data(k.map { $0 ^ 0x36 })
        inner.append(message)
        var outer = Data(k.map { $0 ^ 0x5c })
        outer.append(hash(inner))
        return hash(outer)
    }

    // MARK: - PBKDF2-HMAC-SHA256 (RFC 8018)

    public static func pbkdf2SHA256(password: Data, salt: Data, iterations: Int, keyLength: Int) -> Data {
        precondition(iterations > 0 && keyLength > 0)
        var derived = Data(capacity: keyLength)
        var blockIndex: UInt32 = 1
        while derived.count < keyLength {
            var blockData = salt
            blockData.append(UInt8((blockIndex >> 24) & 0xff))
            blockData.append(UInt8((blockIndex >> 16) & 0xff))
            blockData.append(UInt8((blockIndex >> 8) & 0xff))
            blockData.append(UInt8(blockIndex & 0xff))
            var u = hmacSHA256(key: password, message: blockData)
            var t = [UInt8](u)
            for _ in 1..<iterations {
                u = hmacSHA256(key: password, message: u)
                u.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
                    let ub = raw.bindMemory(to: UInt8.self)
                    for i in 0..<t.count { t[i] ^= ub[i] }
                }
            }
            derived.append(contentsOf: t)
            blockIndex += 1
        }
        return derived.prefix(keyLength)
    }

    // MARK: - helpers

    @inline(__always) private static func rotr(_ x: UInt32, _ n: UInt32) -> UInt32 {
        (x >> n) | (x << (32 - n))
    }

    @inline(__always) private static func rotl(_ x: UInt32, _ n: UInt32) -> UInt32 {
        (x << n) | (x >> (32 - n))
    }
}
