import Foundation
#if canImport(CryptoKit)
import CryptoKit
#endif
#if canImport(CommonCrypto)
import CommonCrypto
#endif

// MARK: - PBKDF2 provider

/// PBKDF2-HMAC-SHA256 abstraction. Production (Apple platforms) uses
/// CommonCrypto's `CCKeyDerivationPBKDF`; Linux test hosts inject/fall back
/// to the pure-Swift implementation so the derivation format itself is
/// verified everywhere against vectors generated by the real web client.
public protocol Pbkdf2Provider {
    /// Derive `keyLength` bytes from `password` and `salt` with PBKDF2-HMAC-SHA256.
    func deriveKey(password: Data, salt: Data, iterations: Int, keyLength: Int) throws -> Data
}

#if canImport(CommonCrypto)
/// CommonCrypto-backed PBKDF2 (`CCKeyDerivationPBKDF`) — the production path
/// on iOS/macOS. Hundreds of times faster than the pure-Swift fallback.
public struct CommonCryptoPbkdf2: Pbkdf2Provider {
    public init() {}

    public func deriveKey(password: Data, salt: Data, iterations: Int, keyLength: Int) throws -> Data {
        var derived = Data(repeating: 0, count: keyLength)
        let status = derived.withUnsafeMutableBytes { derivedPtr in
            password.withUnsafeBytes { passwordPtr in
                salt.withUnsafeBytes { saltPtr in
                    CCKeyDerivationPBKDF(
                        CCPBKDFAlgorithm(kCCPBKDF2),
                        passwordPtr.bindMemory(to: Int8.self).baseAddress,
                        password.count,
                        saltPtr.bindMemory(to: UInt8.self).baseAddress,
                        salt.count,
                        CCPseudoRandomAlgorithm(kCCPRFHmacAlgSHA256),
                        UInt32(iterations),
                        derivedPtr.bindMemory(to: UInt8.self).baseAddress,
                        keyLength
                    )
                }
            }
        }
        guard status == kCCSuccess else {
            throw CryptoError.keyDerivationFailed("CCKeyDerivationPBKDF status \(status)")
        }
        return derived
    }
}
#endif

/// Pure-Swift PBKDF2 (see PureCrypto.swift). Correct but slow at 600 000
/// iterations — used as the default only where CommonCrypto is unavailable.
public struct PureSwiftPbkdf2: Pbkdf2Provider {
    public init() {}

    public func deriveKey(password: Data, salt: Data, iterations: Int, keyLength: Int) throws -> Data {
        PureCrypto.pbkdf2SHA256(password: password, salt: salt, iterations: iterations, keyLength: keyLength)
    }
}

public enum Pbkdf2 {
    /// CommonCrypto on Apple platforms, pure Swift elsewhere.
    public static var defaultProvider: Pbkdf2Provider {
        #if canImport(CommonCrypto)
        return CommonCryptoPbkdf2()
        #else
        return PureSwiftPbkdf2()
        #endif
    }
}

// MARK: - VaultCrypto

/// Symmetric crypto, byte-for-byte compatible with `web/crypto.js`
/// (re-verified against that file and `android/core .../VaultCrypto.kt`):
///
///  - Key derivation: PBKDF2-HMAC-SHA256, 600 000 iterations,
///    salt = UTF-8("vault-internal:" + email), 32-byte AES key.
///  - Encryption: AES-256-GCM, 12-byte random IV, 16-byte tag.
///    Stored form: base64( IV(12) || ciphertext || tag(16) ). WebCrypto
///    appends the tag to the ciphertext, which is exactly CryptoKit's
///    `AES.GCM.SealedBox(combined:)` layout — no re-framing needed.
///  - Shared-vault keys: base64 of 32 raw AES key bytes.
///
/// A wrong master password surfaces as `CryptoError.decryptionFailed` when
/// opening `encrypted_private_key` — there is no other password check anywhere.
public enum VaultCrypto {

    public static let pbkdf2Iterations = 600_000
    public static let saltPrefix = "vault-internal:"
    public static let keyBytes = 32
    public static let gcmIvBytes = 12
    public static let gcmTagBytes = 16

    /// Derive the account AES-256 key from the master password and email.
    /// Mirrors `deriveKey` in web/crypto.js: both password and salt are UTF-8
    /// (including non-ASCII and emoji).
    public static func deriveKey(
        masterPassword: String,
        email: String,
        using provider: Pbkdf2Provider? = nil
    ) throws -> Data {
        guard !masterPassword.isEmpty else { throw CryptoError.invalidArgument("master password must not be empty") }
        guard !email.isEmpty else { throw CryptoError.invalidArgument("email must not be empty") }
        let password = Data(masterPassword.utf8)
        let salt = Data((saltPrefix + email).utf8)
        let key = try (provider ?? Pbkdf2.defaultProvider)
            .deriveKey(password: password, salt: salt, iterations: pbkdf2Iterations, keyLength: keyBytes)
        guard key.count == keyBytes else { throw CryptoError.keyDerivationFailed("provider returned \(key.count) bytes") }
        return key
    }

    /// Split a stored blob into (iv, ciphertext||tag). Pure framing logic,
    /// platform-independent and unit-tested on Linux too.
    public static func splitCombined(base64: String) throws -> (iv: Data, ciphertextAndTag: Data) {
        guard let combined = Data(base64Encoded: base64.trimmingCharacters(in: .whitespacesAndNewlines)) else {
            throw CryptoError.invalidEncoding("ciphertext is not valid base64")
        }
        guard combined.count >= gcmIvBytes + gcmTagBytes else {
            throw CryptoError.ciphertextTooShort(combined.count)
        }
        // Re-wrap in fresh Data values so indices start at 0 for the caller.
        let iv = Data(combined.prefix(gcmIvBytes))
        let rest = Data(combined.dropFirst(gcmIvBytes))
        return (iv, rest)
    }

    /// Import a shared-vault key: base64 of exactly 32 raw AES key bytes,
    /// as produced by `generateVaultKey` in web/crypto.js.
    public static func importVaultKey(base64: String) throws -> Data {
        guard let raw = Data(base64Encoded: base64.trimmingCharacters(in: .whitespacesAndNewlines)) else {
            throw CryptoError.invalidEncoding("vault key is not valid base64")
        }
        guard raw.count == keyBytes else { throw CryptoError.invalidKeyLength(raw.count) }
        return raw
    }

    #if canImport(CryptoKit)

    /// Encrypt a UTF-8 string -> base64(iv || ciphertext || tag). Mirrors `encrypt`.
    public static func encrypt(key: Data, plaintext: String) throws -> String {
        guard key.count == keyBytes else { throw CryptoError.invalidKeyLength(key.count) }
        let symmetric = SymmetricKey(data: key)
        do {
            // AES.GCM.Nonce() draws 12 random bytes from the system CSPRNG.
            let sealed = try AES.GCM.seal(Data(plaintext.utf8), using: symmetric, nonce: AES.GCM.Nonce())
            guard let combined = sealed.combined else { throw CryptoError.encryptionFailed }
            return combined.base64EncodedString()
        } catch let error as CryptoError {
            throw error
        } catch {
            throw CryptoError.encryptionFailed
        }
    }

    /// Decrypt base64(iv || ciphertext || tag) -> UTF-8 string. Mirrors `decrypt`.
    public static func decrypt(key: Data, encoded: String) throws -> String {
        let data = try decryptToData(key: key, encoded: encoded)
        guard let text = String(data: data, encoding: .utf8) else {
            throw CryptoError.decryptionFailed
        }
        return text
    }

    public static func decryptToData(key: Data, encoded: String) throws -> Data {
        guard key.count == keyBytes else { throw CryptoError.invalidKeyLength(key.count) }
        // Validate framing first for precise errors; the WebCrypto combined
        // layout (iv || ct || tag) is exactly what SealedBox(combined:) expects.
        let (iv, rest) = try splitCombined(base64: encoded)
        let symmetric = SymmetricKey(data: key)
        do {
            let box = try AES.GCM.SealedBox(combined: iv + rest)
            return try AES.GCM.open(box, using: symmetric)
        } catch {
            // AuthenticationFailure lands here: wrong key or tampered data.
            throw CryptoError.decryptionFailed
        }
    }

    #else

    // CryptoKit is unavailable (Linux test host). The framing/derivation logic
    // above still runs; actual AES-GCM is Apple-only by design — see README.
    public static func encrypt(key: Data, plaintext: String) throws -> String {
        throw CryptoError.platformUnsupported("AES-GCM requires CryptoKit")
    }

    public static func decrypt(key: Data, encoded: String) throws -> String {
        throw CryptoError.platformUnsupported("AES-GCM requires CryptoKit")
    }

    public static func decryptToData(key: Data, encoded: String) throws -> Data {
        throw CryptoError.platformUnsupported("AES-GCM requires CryptoKit")
    }

    #endif
}
