import XCTest
@testable import MasPasswordCore

/// Verifies VaultCrypto against ciphertexts GENERATED BY THE REAL WEB CLIENT
/// (WebVectors). The AES-GCM cases need CryptoKit and only run on Apple
/// platforms; framing, key import and derivation format run everywhere.
final class VaultCryptoTests: XCTestCase {

    // MARK: framing (platform-independent)

    func testSplitCombinedFraming() throws {
        let (iv, rest) = try VaultCrypto.splitCombined(base64: WebVectors.encVaultName)
        XCTAssertEqual(iv.count, 12)
        XCTAssertGreaterThanOrEqual(rest.count, 16)
        // "Personal" is 8 bytes -> ciphertext+tag must be exactly 24.
        XCTAssertEqual(rest.count, 8 + 16)
    }

    func testSplitCombinedRejectsBadInput() {
        XCTAssertThrowsError(try VaultCrypto.splitCombined(base64: "@@not-base64@@")) {
            guard case CryptoError.invalidEncoding = $0 else { return XCTFail("\($0)") }
        }
        // 27 bytes < IV(12) + tag(16)
        let short = Data(repeating: 1, count: 27).base64EncodedString()
        XCTAssertThrowsError(try VaultCrypto.splitCombined(base64: short)) {
            guard case CryptoError.ciphertextTooShort(27) = $0 else { return XCTFail("\($0)") }
        }
        // Exactly 28 bytes (empty plaintext) is legal framing.
        let minimal = Data(repeating: 1, count: 28).base64EncodedString()
        XCTAssertNoThrow(try VaultCrypto.splitCombined(base64: minimal))
    }

    func testImportVaultKey() throws {
        let key = try VaultCrypto.importVaultKey(base64: WebVectors.vaultKeyB64)
        XCTAssertEqual(key.count, 32)

        XCTAssertThrowsError(try VaultCrypto.importVaultKey(base64: "AAAA")) {
            guard case CryptoError.invalidKeyLength(3) = $0 else { return XCTFail("\($0)") }
        }
        XCTAssertThrowsError(try VaultCrypto.importVaultKey(base64: "!!!")) {
            guard case CryptoError.invalidEncoding = $0 else { return XCTFail("\($0)") }
        }
    }

    func testDeriveKeyRejectsEmptyInputs() {
        XCTAssertThrowsError(try VaultCrypto.deriveKey(masterPassword: "", email: "a@b.c"))
        XCTAssertThrowsError(try VaultCrypto.deriveKey(masterPassword: "x", email: ""))
    }

    // MARK: key derivation at full 600 000 iterations

    /// Fast via CommonCrypto on Apple platforms; the pure-Swift fallback is
    /// exercised too but is slow, so on non-Apple hosts it runs only when
    /// MP_SLOW_TESTS=1 (the format itself is already pinned by the 1000-iter
    /// vector in PureCryptoTests).
    func testDeriveKeyMatchesWebVector() throws {
        #if !canImport(CommonCrypto)
        try XCTSkipUnless(ProcessInfo.processInfo.environment["MP_SLOW_TESTS"] == "1",
                          "600k-iteration pure-Swift PBKDF2 is slow; set MP_SLOW_TESTS=1 to run")
        #endif
        let key = try VaultCrypto.deriveKey(masterPassword: WebVectors.password, email: WebVectors.email)
        XCTAssertEqual(key.hexString, WebVectors.derivedKeyHex)
    }

    // MARK: AES-GCM against real web ciphertexts (CryptoKit platforms)

    private var derivedKey: Data {
        Data(hexString: WebVectors.derivedKeyHex)!
    }

    func testDecryptWebItemBlob() throws {
        #if canImport(CryptoKit)
        let plaintext = try VaultCrypto.decrypt(key: derivedKey, encoded: WebVectors.encItem)
        XCTAssertEqual(plaintext, WebVectors.itemJson)
        #else
        throw XCTSkip("AES-GCM requires CryptoKit (Apple platforms)")
        #endif
    }

    func testDecryptWebVaultName() throws {
        #if canImport(CryptoKit)
        XCTAssertEqual(try VaultCrypto.decrypt(key: derivedKey, encoded: WebVectors.encVaultName), "Personal")
        #else
        throw XCTSkip("AES-GCM requires CryptoKit (Apple platforms)")
        #endif
    }

    func testDecryptSharedItemWithVaultKey() throws {
        #if canImport(CryptoKit)
        let vaultKey = try VaultCrypto.importVaultKey(base64: WebVectors.vaultKeyB64)
        XCTAssertEqual(try VaultCrypto.decrypt(key: vaultKey, encoded: WebVectors.encSharedItem),
                       WebVectors.sharedItemJson)
        #else
        throw XCTSkip("AES-GCM requires CryptoKit (Apple platforms)")
        #endif
    }

    func testEncryptDecryptRoundtrip() throws {
        #if canImport(CryptoKit)
        let message = "ñandú 🔐 line1\nline2 — final"
        let encoded = try VaultCrypto.encrypt(key: derivedKey, plaintext: message)
        // Fresh random IV every time -> different ciphertexts.
        let encoded2 = try VaultCrypto.encrypt(key: derivedKey, plaintext: message)
        XCTAssertNotEqual(encoded, encoded2)
        XCTAssertEqual(try VaultCrypto.decrypt(key: derivedKey, encoded: encoded), message)
        // Framing matches the web layout.
        let (iv, rest) = try VaultCrypto.splitCombined(base64: encoded)
        XCTAssertEqual(iv.count, 12)
        XCTAssertEqual(rest.count, message.utf8.count + 16)
        #else
        throw XCTSkip("AES-GCM requires CryptoKit (Apple platforms)")
        #endif
    }

    func testWrongKeyFailsClosed() throws {
        #if canImport(CryptoKit)
        var wrong = derivedKey
        wrong[0] ^= 0xff
        XCTAssertThrowsError(try VaultCrypto.decrypt(key: wrong, encoded: WebVectors.encVaultName)) {
            XCTAssertEqual($0 as? CryptoError, .decryptionFailed)
        }
        #else
        throw XCTSkip("AES-GCM requires CryptoKit (Apple platforms)")
        #endif
    }

    func testTamperedCiphertextFailsClosed() throws {
        #if canImport(CryptoKit)
        var blob = Data(base64Encoded: WebVectors.encVaultName)!
        blob[blob.count - 1] ^= 0x01 // flip a tag bit
        XCTAssertThrowsError(try VaultCrypto.decrypt(key: derivedKey, encoded: blob.base64EncodedString())) {
            XCTAssertEqual($0 as? CryptoError, .decryptionFailed)
        }
        #else
        throw XCTSkip("AES-GCM requires CryptoKit (Apple platforms)")
        #endif
    }
}
